version: "3.9"

services:
  django:
    build: .
    ports:
      - "8000:8000"
    entrypoint: ./docker-entrypoint.sh
    env_file:
      - .env.test
    depends_on:
      - db
  db:
    image: postgres:13.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.test

volumes:
  postgres_data:
